apiVersion: v1
kind: Service
metadata:
  name: my-frontend
  labels:
    run: my-frontend
    cis.f5.com/as3-tenant: AS3
    cis.f5.com/as3-app: Shared
    cis.f5.com/as3-pool: web_pool

spec:
  ports:
  - name: my-frontend
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    run: my-frontend
