kind: ConfigMap
apiVersion: v1
metadata:
  name: my-frontend
  namespace: default
  labels:
    f5type: virtual-server
data:
  # See the f5-schema table for schema-controller compatibility
  # http://clouddocs.f5.com/containers/latest/releases_and_versioning.html#f5-schema
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "serviceName": "my-frontend",
          "servicePort": 80
        },
        "frontend": {
          "partition": "kubernetes",
          "iapp": "/Common/f5.http.v1.2.0rc7",
          "iappPoolMemberTable": {
            "name": "pool__members",
            "columns": [
                {"name": "addr", "kind": "IPAddress"},
                {"name": "port", "kind": "Port"},
                {"name": "connection_limit", "value": "0"}
            ]
          },
          "iappOptions": {
            "description": "myService_f5.http iApp"
          },
          "iappVariables": {
            "monitor__monitor": "/#create_new#",
            "monitor__response": "none",
            "monitor__uri": "/",
            "net__client_mode": "wan",
            "net__server_mode": "lan",
            "pool__addr": "10.1.10.81",
            "pool__pool_to_use": "/#create_new#",
            "pool__port": "80",
            "asm__use_asm": "/Common/linuxlowpolicy",
            "asm__security_logging":"logall",
            "asm__language": "utf-8"
          }
        }
      }
    }
