kind: ConfigMap
apiVersion: v1
metadata:
  name: my-website
  namespace: default
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.3.json"
  data: |-
    {
      "virtualServer": {
        "frontend": {
          "balance": "round-robin",
          "mode": "http",
          "partition": "kubernetes",
          "virtualAddress": {
            "port": 80
          }
        },
        "backend": {
          "serviceName": "my-website",
          "servicePort": 80,
          "healthMonitors": [{
            "interval": 30,
            "protocol": "http",
            "send": "GET / HTTP/1.0\r\n\r\n",
            "timeout": 91
          }]

        }
      }
    }
