apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-website
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: my-website
    spec:
      containers:
      - image: f5devcentral/f5-demo-httpd:latest
        env:
        - name: F5DEMO_APP
          value: "website"
        - name: F5DEMO_NODENAME
          value: "WWW Kubernetes"
        imagePullPolicy: IfNotPresent
        name: my-website
        ports:
        - containerPort: 80
          protocol: TCP

