kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-as3-configmap
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.1.0",
        "id": "{{ .Release.Name }}",
        "label": "CIS AS3 Example",
        "remark": "Example of using CIS",{{ if .Values.common }}
      {{- include .Values.common.template .  }}{{ end }}
        "AS3": {
          "class": "Tenant"{{- if .Values.applications }},
          "MyApps": {
             "class": "Application",
             "template": "generic"
    {{- $local := dict "first" true }}
    {{- $local := dict "cnt" 8000 }}
    {{- range $items := .Values.applications }}
    {{- range $app, $val := $items }}
      {{- $_ := set $val "cnt" $local.cnt }}      
      {{- if not $local.first }},{{- end }}
      {{- $_ := set $local "first" false  }}
      {{- $_ := set $local "cnt" ($local.cnt |add1)  }}
      {{- include $val.template $val }}
    {{- end }}
    {{- end }}
       }
    {{- end }}
       }
    }
    }
