kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-as3-configmap
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.1.0",
        "id": "{{ .Release.Name }}",
        "label": "CIS AS3 Example",
        "remark": "Example of using CIS",{{- if not .Values.delete }}
      {{- include .Values.common.template .  }}
        "AS3": {
          "class": "Tenant"{{- if not .Values.delete }},
          "MyApps": {
             "class": "Application",
             "template": "generic",
    {{- $local := dict "first" true }}
    {{- range $app, $val := .Values.applications }}      
      {{- if not $local.first }},{{- end }}
      {{- $_ := set $local "first" false  }}
      {{- include $val.template $val }}
    {{- end }}
    {{- end }}
    {{- end }}
       }
       }
    }
    }
