# Default values for f5-as3.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
common:
  template: f5demo.common.basic.v1

applications:
  - frontend:
     name: frontend
     template: f5demo.tcp.v1
     virtualAddress: "10.1.10.81"
     virtualPort: 80
  - website:
     name: website
     template: f5demo.http.v1
     virtualAddress: "10.1.10.80"
  - websitetls:
     name: websitetls
     template: f5demo.https.v1
     virtualAddress: "10.1.10.80"
     serverTLS: '{"bigip":"/Common/_wildcard_.f5demo.com_clientssl"}'

